"""Change application number uniqueness

Revision ID: 0b5df86f2071
Revises: b10457237225
Create Date: 2026-09-25 20:53:09.256856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5df86f2071'
down_revision: Union[str, Sequence[str], None] = 'b10457237225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cases_application_number_key'), 'cases', type_='unique')
    op.create_unique_constraint('uq_cases_jurisdiction_application_number', 'cases', ['jurisdiction', 'application_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cases_jurisdiction_application_number', 'cases', type_='unique')
    op.create_unique_constraint(op.f('cases_application_number_key'), 'cases', ['application_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
