"""add events and event selection

Revision ID: 80e1ec4bd229
Revises: b3e02d72552c
Create Date: 2026-10-04 17:39:58.540388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '80e1ec4bd229'
down_revision: Union[str, Sequence[str], None] = 'b3e02d72552c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

event_selection = sa.Enum(
    "unresolved",
    "new_event",
    "existing_event",
    name="event_selection",
)

event_type = postgresql.ENUM(
    "office_action",
    "application",
    "publication",
    name="event_type",
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_selection.create(op.get_bind(), checkfirst=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', event_type, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('office_action', 'review_office_action', name='task_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tasks_primary_event_task_type', 'tasks', ['event_id', 'task_type'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.add_column('analyses', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column(
        "analyses",
        sa.Column(
            "event_selection",
            event_selection,
            nullable=False,
            server_default="unresolved",
        ),
    )
    op.alter_column(
        "analyses",
        "event_selection",
        server_default=None,
    )
    op.create_foreign_key('fk_analyses_event_id_events', 'analyses', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_analyses_event_id_events', 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'event_selection')
    event_selection.drop(op.get_bind(), checkfirst=True)
    op.drop_column('analyses', 'event_id')
    op.drop_index('uq_tasks_primary_event_task_type', table_name='tasks', postgresql_where=sa.text('is_primary = true'))
    op.drop_table('tasks')
    sa.Enum(name="task_type").drop(op.get_bind(), checkfirst=True)
    op.drop_table('events')
    # ### end Alembic commands ###
