"""Create case tables

Revision ID: b10457237225
Revises: 
Create Date: 2026-09-24 15:48:02.079860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10457237225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_reference', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('publication_number', sa.String(length=50), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('grant_number', sa.String(length=50), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('agent_reference', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number'),
    sa.UniqueConstraint('internal_reference')
    )
    op.create_table('case_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_case_id', sa.Integer(), nullable=False),
    sa.Column('target_case_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('direct_parent', 'priority', name='case_relationship_type'), nullable=False),
    sa.CheckConstraint('source_case_id <> target_case_id', name='ck_case_relationship_not_self'),
    sa.ForeignKeyConstraint(['source_case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['target_case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_case_id', 'target_case_id', 'relationship_type', name='uq_case_relationship')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_relationships')
    op.drop_table('cases')
    # ### end Alembic commands ###
