"""add analyses table

Revision ID: b1dbe9a4c535
Revises: e655f05b42ae
Create Date: 2026-10-01 17:49:42.012919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1dbe9a4c535'
down_revision: Union[str, Sequence[str], None] = 'e655f05b42ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correspondence_id', sa.Integer(), nullable=False),
    sa.Column('internal_reference', sa.String(length=50), nullable=True),
    sa.Column('jurisdiction', sa.String(length=2), nullable=True),
    sa.Column('application_number', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.Enum('office_action', 'application', 'publication', name='event_type'), nullable=True),
    sa.Column('office_action_type', sa.Enum('Office Action', 'Office Action 1MO', 'Office Action 2MO', 'Office Action 3MO', 'Office Action 4MO', name='office_action_type'), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('agent_notification_date', sa.Date(), nullable=True),
    sa.Column('agent_reported_due_date', sa.Date(), nullable=True),
    sa.Column('calculated_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['correspondence_id'], ['correspondences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correspondence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    sa.Enum(name="office_action_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="event_type").drop(op.get_bind(), checkfirst=True) 
    # ### end Alembic commands ###
