"""add analysis review status

Revision ID: b3e02d72552c
Revises: b1dbe9a4c535
Create Date: 2026-10-03 12:42:45.258849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e02d72552c'
down_revision: Union[str, Sequence[str], None] = 'b1dbe9a4c535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

analysis_status = sa.Enum(
    "pending_review",
    "approved",
    name="analysis_status",
)

def upgrade() -> None:
    """Upgrade schema."""
    analysis_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('status', analysis_status, nullable=False, server_default="pending_review"))
    op.alter_column("analyses", "status", server_default=None)
    op.add_column('analyses', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'approved_at')
    op.drop_column('analyses', 'status')
    analysis_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
