"""add email metadata to correspondence

Revision ID: e655f05b42ae
Revises: f3b96939bff0
Create Date: 2026-09-28 16:27:59.881185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e655f05b42ae'
down_revision: Union[str, Sequence[str], None] = 'f3b96939bff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correspondences', sa.Column('email_subject', sa.Text(), nullable=True))
    op.add_column('correspondences', sa.Column('email_sender', sa.Text(), nullable=True))
    op.add_column('correspondences', sa.Column('email_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('correspondences', sa.Column('email_message_id', sa.String(), nullable=True))
    op.add_column('correspondences', sa.Column('body_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correspondences', 'body_text')
    op.drop_column('correspondences', 'email_message_id')
    op.drop_column('correspondences', 'email_date')
    op.drop_column('correspondences', 'email_sender')
    op.drop_column('correspondences', 'email_subject')
    # ### end Alembic commands ###
