"""add source storage path to correspondence

Revision ID: f3b96939bff0
Revises: 5e6f5c8dac6b
Create Date: 2026-09-28 16:14:03.120405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b96939bff0'
down_revision: Union[str, Sequence[str], None] = '5e6f5c8dac6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correspondences', sa.Column('source_storage_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correspondences', 'source_storage_path')
    # ### end Alembic commands ###
