"""link tasks to correspondences

Revision ID: fae90352c4f2
Revises: dc7e0939d1d6
Create Date: 2026-10-07 16:31:54.872556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae90352c4f2'
down_revision: Union[str, Sequence[str], None] = 'dc7e0939d1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('correspondence_id', sa.Integer(), nullable=False))
    op.alter_column('tasks', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(
        "fk_tasks_correspondence_id_correspondences",
        "tasks",
        "correspondences",
        ["correspondence_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_tasks_correspondence_id_correspondences",
        "tasks",
        type_="foreignkey",
    )
    op.alter_column('tasks', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'correspondence_id')
    # ### end Alembic commands ###
